export const PRIVATE_DATA = {
  spaseID: process.env.NEXT_PUBLIC_SPACE_ID_OCEAN_INSIGHT_CENTER,
  accessId: process.env.NEXT_PUBLIC_ACCESS_ID_OCEAN_INSIGHT_CENTER,
  keyID: process.env.NEXT_PUBLIC_KEY_ID_OOCEAN_INSIGHT_CENTER,
};
